### ISSUE TITLE
Invalid Module

### ISSUE THREAD

**Issue by zeezooX** [amrufathy/Snake#1]
Running main.py results in a runtime error:

> Traceback (most recent call last):
>   File "/home/zeezoox/Documents/Snake-master/src/main.py", line 1, in <module>
>     from src.game_utils.game_setup import *
> ImportError: No module named 'src'

Please fix this ASAP!

**Comment by mmghannam** [comment]
Please send a screenshot for the pycharm cofiguartion for the run.

**Comment by zeezooX** [comment]
I use Visual Studio Code☺

**Comment by mmghannam** [comment]
Try this fix and tell us what happens, as we're not able to recreate the issue
https://stackoverflow.com/questions/4761041/python-import-src-modules-when-running-tests

**Comment by zeezooX** [comment]
No solution found yet!

**Comment by amrufathy** [comment]
Try moving [main.py](https://github.com/amrufathy/Snake/blob/master/src/main.py) to the project's root directory.

**Comment by zeezooX** [comment]
Solved! Thanks a lot?
